# Generated by Django 3.1.7 on 2021-04-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210402_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Chef', 'Chef')], default='Medium', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1),
        ),
    ]
